### ISSUE TITLE
Looking for an alternative to null-ls

### ISSUE THREAD

**Issue by yigityazicilar** [UnikMask/UnikVim#1]
The maintainer of null-ls is archiving it. Which means that it will no longer get any updates. This might cause issues with newer versions of Neovim. I suggest that we look into alternatives to keep a similar experience.

jose-elias-alvarez/null-ls.nvim#1621

**Comment by OcEaNvS** [comment]
jose-elias-alvarez/null-ls.nvim/#1621

**Comment by UnikMask** [comment]
May have found a solution in replacing null-ls with [nvimtools/none-ls.nvim](https://github.com/nvimtools/none-ls.nvim).
It's simply a fork of the old null-ls which should hopefully keep maintaining for the newer Neovim versions.

**Comment by UnikMask** [comment]
Replaced null-ls with none-ls, see [c591437](https://github.com/UnikMask/UnikVim/commit/c591437086e82e4468bd88db4d20f389297f53ad). Closing issue now.
